name: Deploy to release pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  create_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve version code for release
        run: |
          echo "::set-output name=VERSION_CODE::$(${{ github.workspace }}/gradlew -q printVersionCode)"
        id: android_code

      - name: Set version code environment variable
        run: |
          echo "VERSION_CODE=${{steps.android_code.outputs.VERSION_CODE}}" >> $GITHUB_ENV

      - name: Create changelog for fastlane
        uses: 1arp/create-a-file-action@0.3
        with:
          path: "fastlane/metadata/android/en-US/changelogs"
          file: "${{ env.VERSION_CODE }}.txt"
          content: |
            Thank you for using my app! I regularly update it to improve performance and add new features. This update includes bug fixes and performance improvements to make the app run smoother. Please let me know if you have any issues by opening a Github issue.
