name: Deploy to release pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  create_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Retrieve version code for release
        run: |
          echo "::set-output name=VERSION_CODE::$(${{ github.workspace }}/gradlew -q printVersionCode)"
        id: android_code

      - name: Set version code environment variable
        run: |
          echo "VERSION_CODE=${{steps.android_code.outputs.VERSION_CODE}}" >> $GITHUB_ENV

      - name: Create changelog for fastlane
        run: |
          cd fastlane/metadata/android/en-US
          echo "Thank you for using my app! I regularly update it to improve performance and add new features. This update includes bug fixes and performance improvements to make the app run smoother. Please let me know if you have any issues by opening a Github issue." > ${{ env.VERSION_CODE }}.txt

      - name: Commit changelog
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add fastlane/metadata/android/en-US/${{ env.VERSION_CODE }}.txt
          git commit -m "Add changelog for release ${{ env.VERSION_CODE }}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
