name: Deploy to release pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  create_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve version code for release
        run: |
          echo "::set-output name=VERSION_CODE::$(${{ github.workspace }}/gradlew -q printVersionCode)"
        id: android_code

      - name: Set version code environment variable
        run: |
          echo "VERSION_CODE=${{steps.android_code.outputs.VERSION_CODE}}" >> $GITHUB_ENV

      - name: Create changelog for fastlane
        uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: "doubleangels/NextDNSManager"
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: "fastlane/metadata/android/en_us/changelogs/${{ env.VERSION_CODE }}.txt}}"
          COMMIT_MESSAGE: "Update release notes"
