name: Test changelog

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  test-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changelog content from fastlane
        id: read_file
        run: |
          file_content=$(cat whatsnew/whatsnew-en-US)
          echo "::set-output name=file_content::$file_content"
        shell: bash

      - name: Create changelog for fastlane
        run: |
          cd fastlane/metadata/android/en-US/changelogs
          echo {{ steps.read_file.outputs.file_content }} > test.txt

      - name: Commit changelog for fastlane
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add fastlane/metadata/android/en-US/changelogs/test.txt
          git commit -m "Add changelog test"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
