name: Test dependabot pull request

on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from Dependabot
        id: dependabot-check
        run: echo "::set-output name=is_dependabot::${{ contains(github.event.pull_request.user.login, 'dependabot') }}"

  build:
    runs-on: ubuntu-latest
    if: ${{ needs.check-pr.outputs.is_dependabot == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release build with Gradle
        run: ./gradlew assembleRelease
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
